# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Fonksiyon Testleri ve PyPI Yükle

on: [push, pull_request]

jobs:
  KekikTest:
    name: Fonksiyon Testleri

    strategy:
      matrix:
        python-version: ["3.10.6"]
        os: ["ubuntu-latest", "windows-latest", "macos-11.0"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v2

      - name: Python ${{ matrix.python-version }} Sürümü Yükleniyor
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Kütüphaneyi Yükle
        run: pip install .

      - name: Pytest'i Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test Dosyalarını Çalıştır
        run: pytest

      # - name: Test Dosyalarını Windows Ortamda Çalıştır
      #   if: matrix.os == 'windows-latest'
      #   shell: cmd
      #   run: |
      #     cd ${{ github.workspace }}/Testler
      #     FOR %%i in (*.py) DO python -m pytest %%i

      # - name: Test Dosyalarını Posix Ortamda Çalıştır
      #   if: matrix.os != 'windows-latest'
      #   run: pytest Testler/*

  PyPIYukleyici:
    name: PyPI Yükleyici
    runs-on: ubuntu-latest
    needs: KekikTest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v2

      - name: Python 3.10.6 Yükle
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Kütüphaneyi PyPI'ye Yükle
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py bdist_wheel sdist
          twine check dist/*
          python -m twine upload dist/*
          rm -rf build/
          rm -rf dist/
          rm -rf -- *.egg-info/