# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: KekikSpatula Fonksiyon Testleri

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  KekikTest:
    strategy:
      matrix:
        python-version: ["3.10.6"]
        os: ["ubuntu-latest", "windows-latest", "macos-11.0"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v2

      - name: Python ${{ matrix.python-version }} Sürümü Yükleniyor
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Kütüphaneyi Yükle
        run: pip install .

      - name: Pytest'i Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test Dosyalarını Windows Ortamda Çalıştır
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          cd ${{ github.workspace }}/Testler
          FOR %%i in (*.py) DO python -m pytest %%dosya

      - name: Test Dosyalarını Posix Ortamda Çalıştır
        if: matrix.os != 'windows-latest'
        run: pytest Testler/*
